#!/usr/bin/env bash
#5-4_bad_luck_8_is_your_chance

counter=1
while(( counter<=10 )); do
	if(( counter==4 )); then
		echo "bad luck"
	elif(( counter==8 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
