#!/usr/bin/env bash
# 6-superstitious_numbers

i=1
while (( i <= 20 )); do
    echo "$i"
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((i++))
done

